build:
  version: "Yes i am in QA and this output is after the runtime execution modification for webhook changes 12344r678r5684"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
spring:
  application:
    name: "qa"
